apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tigera-federation-remote-cluster
rules:
- apiGroups: [""]
  resources:
    - nodes
  verbs:
    - list
    - watch
- apiGroups: [""]
  resources:
    - pods
  verbs:
    - list
    - watch
- apiGroups: [""]
  resources:
    - services
  verbs:
    - list
    - watch
- apiGroups: ["crd.projectcalico.org"]
  resources:
    - hostendpoints
    - networksets
    - globalnetworksets
    - networkpolicies
    - globalnetworkpolicies
    - felixconfigurations
    - kubecontrollersconfigurations
    - ippools
    - profiles
  verbs:
    - list
    - watch
- apiGroups: ["projectcalico.org"]
  resources:
    - hostendpoints
    - networksets
    - globalnetworksets
    - networkpolicies
    - globalnetworkpolicies
    - felixconfigurations
    - kubecontrollersconfigurations
    - ippools
    - profiles
  verbs:
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tigera-federation-remote-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tigera-federation-remote-cluster
subjects:
- kind: ServiceAccount
  name: tigera-federation-remote-cluster
  namespace: kube-system
---
# Additional permissions for Typha to access the kubeconfig secret
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: calico-typha-federation
  namespace: {{ .Values.peerCluster.namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
  resourceNames: ["{{ .Values.peerCluster.secretName }}"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: calico-typha-federation
  namespace: {{ .Values.peerCluster.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: calico-typha-federation
subjects:
- kind: ServiceAccount
  name: calico-typha
  namespace: calico-system
