apiVersion: v1
kind: Secret
metadata:
  name: tigera-federation-remote-cluster
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: "tigera-federation-remote-cluster"
type: kubernetes.io/service-account-token
